### ISSUE TITLE
Getting an error when sending a basic payload in Heroku

### ISSUE THREAD

**Issue by brainded** [jurgelenas/pdfify-server#1]
Unsure if it is the environment or the software but I am receiving this error for every hit to the service:

{"message":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/tmp/010d3900-005e-498e-93c8-639a6ff00d56"},"error":true}

Any help would be appreciated. It is my first time working with a Node app and this error gives me little to go on.

**Comment by jurgelenas** [comment]
1. Are you using https://github.com/jurgelenas/node-pdfify-client to make API requests?
2. Copy here pdfify-server full heroku log when this error occurs

**Comment by brainded** [comment]
I was using RestRequest from C# to call the API using a POST on Heroku. The Posted Json is attached.

Here is the Heroku Logs when the execution completes:

2017-01-21T23:32:20.983240+00:00 heroku[router]: at=info method=POST path="/convert" host=virtuoushtmltopdf.herokuapp.com request_id=6cd7d278-809d-4027-8713-f32a0f1bad56 fwd="184.176.113.156" dyno=web.1 connect=0ms service=78ms status=400 bytes=333
2017-01-21T23:32:20.990046+00:00 app[web.1]: [0mPOST /convert [33m400 [0m71.513 ms - 121[0m

[payload.zip](https://github.com/jurgelenas/pdfify-server/files/721570/payload.zip)

This is of course after I made changes from previous logged errors complaining about a null sheet object so if you run your build you will get those errors first.

https://github.com/brainded/pdfify-server/commit/6f1595c9d95faf3051ce61c15a8d5dbda032a4a8

I made an additional change to how the html content is set:

https://github.com/brainded/pdfify-server/commit/0029e6f7206ff045f162da1d9abef2e440177ff9

And I am now getting the following error which provides even less information:

{"message":{},"error":true}

**Comment by jurgelenas** [comment]
[brainded@0029e6f](https://github.com/brainded/pdfify-server/commit/0029e6f7206ff045f162da1d9abef2e440177ff9) caused you to receive ```{"message":{},"error":true}```.

Your [brainded@6f1595c](https://github.com/brainded/pdfify-server/commit/6f1595c9d95faf3051ce61c15a8d5dbda032a4a8) commit fixes null stylesheet error, but if HTML document does not have any stylesheets - page zoom no longer works.

[c0f969f](https://github.com/jurgelenas/pdfify-server/commit/c0f969f3752b85f3fa7a21e2506c203c25c7aeb7) should fix your issues. My advice: fix javascript errors in your document and disable chart animations. It is possible that pdf document will be rendered with animations still in progress.

**Comment by jurgelenas** [comment]
@brainded would you be interested in writing C# client library? It would be a great addition to pdfify-server and you could use it in your projects.

Currently there is only Node.js client library: https://github.com/jurgelenas/node-pdfify-client

**Comment by brainded** [comment]
Thanks for taking a stab at it! I will take a look later today. A C# Client would be pretty easy to spin up and I would be happy to!

**Comment by jurgelenas** [comment]
Ok! :)

Please verify that my commit fixed your issues with pdfify-server. If that is correct I will be able to close this issue.
